version: "3"
services:
  app:
    build:
      context: "docker/app/"
    ports:
      - 80:80
      - 8000:80
    working_dir: /var/www
    volumes:
      - "./www/:/var/www"
      - "./docker/app/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - "./docker/app/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/msmtp/msmtprc:/etc/msmtprc"
    depends_on:
      - mysql
      - mailhog
  mysql:
    build:
      context: "docker/mysql/"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=kokoro_db
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    volumes:
      - "./docker/mysql/storage/:/var/lib/mysql"
      - "./docker/mysql/initdb/:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/amd64
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=pass
    depends_on:
      - mysql
  mailhog:
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - "8025:8025"
      - "1025:1025"
volumes:
  storage: